services:
  pathcov:
    environment:
      - ENV=dev

    volumes:
      - ./development/data:/data
      - ../pathcov:/pathcov-project/pathcov
      - ../coverage-agent:/pathcov-project/coverage-agent

  jdart:
    volumes:
      - ./development/data:/data
      - ../../jdart/:/jdart-project/jdart
