services:
  pathcov:
    environment:
      - ENV=dev

    volumes:
      - ./development/data:/data
      - ../pathcov:/pathcov-project/pathcov

  jdart:
    volumes:
      - ./development/data:/data
      - ../../jdart/:/jdart-project/jdart
