# ============================================================
# SUT configuration
# ============================================================
sut:
  # Paths should be relative to the root given in the .env file
  compiled_root: target/classes
  test_root: target/test-classes
  source_root: src/main/java
  # Optional deps_class_path: specify the classpath for the dependencies (colon-separated, test scope)
  # The paths should be absolute and be in the DEPS_DIR defined in the .env
  # if not specified, it will be auto-detected from the SUT_DIR, and should be in the DEPS_DIR defined in the .env
  # deps_class_path:

  # Optional junit_options: specify junit run options (e.g., --select-class com.example.MyTestClass)
  # if not specified, --scan-classpath will be used
  junit_options: --select-class com.thealgorithms.maths.LongDivisionTest

test_generation:
  generated_tests_dir_out: data/generated-tests

target:
  class: com.thealgorithms.maths.LongDivision
  method: divide
  return: int
  parameters:
    - name: dividend
      type: int
    - name: divisor
      type: int

analysis:
  project_prefixes:
    - com.thealgorithms.maths
