# ============================================================
# SUT configuration
# ============================================================
# Paths should be relative to the root given in the .env file
sut:
  compiled_root: out/production/jdart-examples
  test_root: out/test/jdart-examples
  source_root: src/examples
  
test_generation:
  generated_tests_dir_out: data/generated-tests

target:
  class: examples.OverallJDartExample
  method: foo
  return: int
  parameters:
    - name: n
      type: int
    - name: m
      type: int
    - name: limit
      type: long
    - name: scale
      type: double
    - name: flag
      type: boolean

analysis:
  project_prefixes:
    - examples
