# ============================================================
# SUT configuration
# ============================================================
# Paths should be relative to the root given in the .env file
sut:
  compiled_root: target/classes
  test_root: target/test-classes
  source_root: src/main/java
  run_tests_command: mvn -Dtest=LongDivisionTest test
  
test_generation:
  generated_tests_dir_out: data/generated-tests

target:
  class: com.thealgorithms.maths.LongDivision
  method: divide
  return: int
  parameters:
    - name: dividend
      type: int
    - name: divisor
      type: int

analysis:
  project_prefixes:
    - com.thealgorithms.maths
